import { GET } from "./api/movie-search/route";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout() {
  return (
    <div className="">
      <main></main>
    </div>
  );
}
