
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout() {
  return (
    <div className="">
      <main></main>
    </div>
  );
}
